"""Customer-problem themes built on the CFPB's product / issue / sub-issue fields.

Each theme is written as the question a customer would bring to a help center or
chatbot. Rules are checked in order; the first match wins. (product, issue, sub_issue)
are case-insensitive regexes matched against the CFPB fields.
"""
import re

THEMES = [
    # id, label, customer question, search query for help content, rules
    ("zelle_scam", "Zelle / P2P scam or fraud",
     "I was scammed (or my account was used) through Zelle. Can I get my money back?",
     "zelle scam fraud victim get money back reimbursement sent money to scammer impersonation",
     [("money transfer", "fraud or scam", ".*")]),
    ("transfer_problem", "Transfer didn't arrive, wrong amount, or can't be traced",
     "My transfer / Zelle / wire didn't arrive or went to the wrong place. Where is my money?",
     "zelle payment not received pending failed canceled wrong recipient wire transfer where is my money",
     [("money transfer", "other transaction problem|money was not available|wrong amount|unauthorized transactions|customer service|disclosures|managing|.*", ".*")]),
    ("card_fraud", "Charges or withdrawals I didn't make",
     "There's a charge or withdrawal on my account that I didn't make. What happens now?",
     "unauthorized charge fraud report transaction i didn't make zero liability claim lost stolen card",
     [("credit card", "purchase shown on your statement", "did not purchase"),
      ("checking", "charging your account", "not authorized")]),
    ("cc_dispute_stuck", "Card dispute denied, stuck, or reversed",
     "I disputed a charge and the bank denied it, reversed my credit, or it's taking forever. What are my options?",
     "dispute status how long does a dispute take dispute denied provisional credit reversed appeal claim",
     [("credit card", "purchase shown on your statement|investigation into an existing problem", "resolving a dispute|overcharged|statement of dispute|difficulty submitting|.*purchase")]),
    ("deposit_hold", "Deposit held, missing, or reversed",
     "My deposit is on hold, missing, or was reversed. When can I use my money?",
     "deposit hold when will funds be available check deposit missing reversed mobile deposit cashing a check",
     [("checking", "managing an account", "deposits (and|or) withdrawals|cashing a check")]),
    ("debit_atm", "Debit card or ATM problem",
     "My debit card was declined / the ATM didn't give me cash / I need to dispute a debit transaction.",
     "debit card declined not working atm did not dispense cash atm error dispute debit transaction replace card",
     [("checking", "managing an account", "debit or atm card")]),
    ("bank_closed", "Bank closed my account without explanation",
     "Why did the bank close my account, and what happens to my money?",
     "why was my account closed bank closed my account restricted frozen reason",
     [(".*", "clos", "company closed your account")]),
    ("closed_funds", "Can't get my money back from a closed account",
     "My account was closed. When and how do I get my remaining balance?",
     "closed account remaining balance check mailed cashier's check how long receive funds after closure",
     [("checking", "clos", "funds not received")]),
    ("cant_close", "Can't close my account",
     "How do I close my account, and why won't it close?",
     "how do i close my account",
     [(".*", "clos", "can't close")]),
    ("access_locked", "Locked out, frozen, or can't access my account",
     "My account is locked, frozen, or restricted. How do I get back in?",
     "account locked frozen restricted can't log in verify identity unlock online banking access",
     [("checking", "managing an account", "accessing account")]),
    ("payment_mishandled", "Transfer or payment not handled as instructed / bank error",
     "I made a payment or transfer and the bank didn't handle it the way I asked (or made an error).",
     "transfer between accounts not processed bill pay payment not sent bank error cutoff time processing",
     [("checking", "managing an account", "funds not handled|banking errors|making or receiving payments")]),
    ("recurring_withdrawal", "Can't stop a recurring charge, or wrong-day / wrong-amount withdrawal",
     "How do I stop a merchant or company from taking money out of my account?",
     "stop payment recurring automatic payment ach debit revoke authorization merchant withdrawal wrong amount",
     [("checking", "charging your account", "stop withdrawals|wrong day")]),
    ("id_theft_account", "Account or card opened in my name (identity theft)",
     "Someone opened an account or card in my name. How do I report it and clean it up?",
     "identity theft account opened in my name without permission report fraud new account",
     [(".*", ".*", "without my consent|identity theft|belongs to someone else")]),
    ("cant_open", "Can't open an account / didn't get the advertised terms",
     "Why can't I open an account, and where's the bonus or terms I was promised?",
     "open an account denied requirements verification bonus offer terms",
     [("checking", "opening an account", ".*")]),
    ("overdraft", "Overdraft, NSF, and account fees",
     "Why was I charged an overdraft or account fee, and can it be refunded?",
     "overdraft fee why charged refund nsf returned item available balance monthly maintenance fee",
     [("checking", "funds being low", ".*"), ("checking", "managing an account", "fee problem")]),
    ("cc_fees_interest", "Credit card fees and interest",
     "Why was I charged this fee or interest on my credit card?",
     "credit card late fee interest charge annual fee apr increase refund fee",
     [("credit card", "fees or interest", ".*")]),
    ("cc_payment", "Credit card payment problems",
     "My card payment didn't post, was applied wrong, or I never got a bill.",
     "credit card payment not posted payment due date how payments are applied statement not received autopay",
     [("credit card", "making payments", ".*")]),
    ("credit_report", "Wrong information on my credit report",
     "The bank is reporting something wrong to the credit bureaus. How do I get it fixed?",
     "credit report incorrect credit bureau reporting dispute error late payment reported",
     [(".*", "incorrect information on your report|investigation into an existing problem", ".*")]),
    ("hardship", "Struggling to pay / need a payment plan",
     "I can't make my payments. What hardship or payment-plan options do I have?",
     "financial hardship payment plan can't pay assistance program lower payment",
     [("credit card", "struggling to pay", ".*")]),
    ("collections_dispute", "Collections on a debt I don't owe or can't verify",
     "I'm being collected on for a debt that isn't mine, is already paid, or is the wrong amount.",
     "debt collection verify debt not mine already paid wrong amount charged off account recovery",
     [("debt collection", "debt not owed|false statements|written notification", ".*")]),
    ("collections_threats", "Collections calls, threats, and credit-damage warnings",
     "Collections keeps calling or threatening to hurt my credit. What are my rights?",
     "collections calls credit damage charged off recovery department contact",
     [("debt collection", ".*", ".*")]),
    ("rewards_promo", "Rewards, promo, or balance-transfer terms not honored",
     "I didn't get the rewards, promo rate, or balance-transfer terms I was promised.",
     "rewards points not received promotional offer balance transfer terms cash back",
     [("credit card", "rewards|advertising|other features", "rewards|advertised|balance transfer|misleading")]),
    ("cc_access", "Card application, credit limit, or card won't work",
     "My application was denied or delayed, my limit changed, or my card won't work.",
     "application status denied credit limit increase decrease card declined",
     [("credit card", "getting a credit card|trouble using your card", ".*")]),
    ("service_other", "Other / customer-service problems",
     "Other issues and poor customer-service experiences.",
     "customer service contact",
     [(".*", ".*", ".*")]),
]


def assign(product, issue, sub_issue):
    p, i, s = (str(x or "").lower() for x in (product, issue, sub_issue))
    for tid, *_rest, rules in THEMES:
        for rp, ri, rs in rules:
            if re.search(rp, p) and re.search(ri, i) and re.search(rs, s):
                return tid
    return "service_other"
